name: Deploy BenchRacers Infrastructure

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main  

jobs:
  terraform:
    name: Apply Terraform Changes
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Set up AWS credentials
        run: |
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
          echo "AWS_DEFAULT_REGION=us-west-2" >> $GITHUB_ENV

      - name: Terraform Init
        run: terraform init

      - name: Import existing resources
        run: |
          import_if_not_exists() {
            terraform state show "$1" >/dev/null 2>&1 || terraform import "$@"
          }

          import_if_not_exists aws_cloudwatch_log_group.benchracers_api_logs /benchracers/api/calls
          import_if_not_exists aws_iam_role.ec2_cloudwatch_role benchracers-ec2-cloudwatch-role
          import_if_not_exists aws_iam_instance_profile.ec2_profile benchracers-ec2-cloudwatch-profile
          import_if_not_exists aws_s3_bucket.benchracers_photos benchracers-photos
          import_if_not_exists aws_iam_policy.s3_access_policy arn:aws:iam::060795900722:policy/benchracers-s3-access-policy
          import_if_not_exists aws_security_group.alb_sg sg-009cd1df10a9e80c1
          import_if_not_exists aws_lb_target_group.benchracers_target_group arn:aws:elasticloadbalancing:us-west-2:060795900722:targetgroup/benchracers-tg/42a15355d3e579b2
          import_if_not_exists aws_lb.benchracers_alb arn:aws:elasticloadbalancing:us-west-2:060795900722:loadbalancer/app/benchracers-alb/c9a52193f6a69ce6
          import_if_not_exists aws_autoscaling_group.benchracers_asg benchracers-asg




      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve
        
      - name: Trigger ASG Instance Refresh
        run: |
          aws autoscaling start-instance-refresh \
            --auto-scaling-group-name benchracers-asg \
            --strategy Rolling
